import { Providers } from "@/redux/provider";
import "./globals.css";

export const metadata = {
  title: "TK Ventures Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
